filetype: csv
dataset_name: agg_match_stats_2
inbound_delimeter: ","
oubound_delimeter: "|"
skip_leading_rows: 1
columns : ['date', 'game_size', 'match_id', 'match_mode', 'party_size',
       'player_assists', 'player_dbno', 'player_dist_ride', 'player_dist_walk',
       'player_dmg', 'player_kills', 'player_name', 'player_survive_time',
       'team_id', 'team_placement']
